# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

#python -m flask run
#docker build --tag python-docker
# docker images
# docker run python-docker
#docker run -d -p 8000:5000 python-docker
#curl localhost :8000